### ISSUE TITLE
Loading orbit tree from file does not seem to set `leaves`

### ISSUE THREAD

**Issue by thpar** [biointec/jesse#2]
When an `OrbitTree` is read from file with constructor `OrbitTree(String filename)` the `leaves` attribute stays empty, resulting in a `NullpointerException`

```
Exception in thread "main" java.lang.NullPointerException
        at equations.EquationGenerator.generateEquations(EquationGenerator.java:38)
        at codegenerating.DanglingInterpreter.<init>(DanglingInterpreter.java:60)
        at codegenerating.UI.run(UI.java:110)
        at codegenerating.UI.main(UI.java:69)
```

**Comment by IneMelckenbeeck** [comment]
Fixed

**Comment by thpar** [comment]
There might still be issues here.
In this example I'm counting order 4 graphlets.

First with the `OrbitTree` in memory (and writing it to file):
```
Welcome to the Jesse orbit counter.
Which order of graphlets would you like to count?
4
Do you want to generate the orbits? (y/n)
n
Do you want to use the standard file for the orbit numbering? (y/n)
y
Do you want to generate a new orbit tree? (y/n)
y
Do you want to save the tree? (y/n)
y
Enter the file name for the orbit tree:
/home/thpar/tmp/tmptree-4
Enter the file name for the graph:
/home/thpar/git/jesse/graphs/randomgraph-100-1000.txt
Enter the file name for the results:
/home/thpar/tmp/output4
Reading graphlets...
Read graphlets in 0.026017560000000002s
Generating tree...
Generated tree in 0.006782985s
Reading graph...
Read graph in 0.061664562000000006s
Calculating common neighbours...
Calculated common neighbours in 0.038794079s
Counting orbits...
Counted orbits in 0.090194227s
Saving results...
Saved results in 0.0026619250000000003s
```

then again, but using the `OrbitTree` I saved last time:
```
Welcome to the Jesse orbit counter.
Which order of graphlets would you like to count?
4
Do you want to generate the orbits? (y/n)
n
Do you want to use the standard file for the orbit numbering? (y/n)
y
Do you want to generate a new orbit tree? (y/n)
n
Enter the file name for the orbit tree:
/home/thpar/tmp/tmptree-4
Enter the file name for the graph:
/home/thpar/git/jesse/graphs/randomgraph-100-1000.txt
Enter the file name for the results:
/home/thpar/tmp/output4
Reading graphlets...
Read graphlets in 0.022934929s
Reading graph...
Read graph in 0.051792346s
Calculating common neighbours...
Calculated common neighbours in 0.039366693s
Counting orbits...
Exception in thread "main" java.lang.NullPointerException
        at graph.DanglingList.addInOrder(DanglingList.java:214)
        at codegenerating.DanglingInterpreter.addNodeAction(DanglingInterpreter.java:129)
        at tree.AddNodeNode.walkTree(AddNodeNode.java:119)
        at codegenerating.DanglingInterpreter.conditionAction(DanglingInterpreter.java:172)
        at tree.ConditionNode.walkTree(ConditionNode.java:127)
        at codegenerating.DanglingInterpreter.addEdgeAction(DanglingInterpreter.java:164)
        at tree.AddEdgeNode.walkTree(AddEdgeNode.java:164)
        at codegenerating.DanglingInterpreter.addNodeAction(DanglingInterpreter.java:150)
        at tree.AddNodeNode.walkTree(AddNodeNode.java:119)
        at codegenerating.DanglingInterpreter.addNodeAction(DanglingInterpreter.java:150)
        at tree.AddNodeNode.walkTree(AddNodeNode.java:119)
        at codegenerating.DanglingInterpreter.run(DanglingInterpreter.java:187)
        at codegenerating.UI.run(UI.java:113)
        at codegenerating.UI.main(UI.java:69)
```

**Comment by thpar** [comment]
This problem doesn't show when searching for order 3.

**Comment by IneMelckenbeeck** [comment]
Okay, fixed again... forgot to add depth calculation when reading the tree.
